### ISSUE TITLE
SASS Variable replacement ignored for CSS 4 variables

### ISSUE THREAD

**Issue by TristanPct** [failwyn/WebCompiler#12]
### Installed product versions
- Visual Studio: 2022
- This extension: 1.14.0

### Description
I have SASS file with variables injected as CSS 4 variables values, and they're not replaced by the compilation.

### Source file
```scss
$test: 1.5rem;
$test2: 2rem;

:root {
    --my-var: $test;
}

.myClass {
    --my-var: $test2;
}
```

### Current behavior
Generated CSS from this extension:

```css
:root {
  --my-var: $test;
}

.myClass {
  --my-var: $test2;
}
```

### Expected behavior
Generated CSS from the original extension (VS 2019):

```css
:root {
  --my-var: 1.5rem; }

.myClass {
  --my-var: 2rem; }
```
