### ISSUE TITLE
Compiled SASS Stylesheet References SASS Variables in CSS

### ISSUE THREAD

**Issue by donkerrigan** [failwyn/WebCompiler#14]
### Installed product versions
- Visual Studio: 2022 (17.0.1)
- This extension: 1.14.1

### Description
SASS compilation is including references to SASS variables in css output when using mixins that assign css variables

### Steps to recreate
1. Create a SASS stylesheet that references a mixin from another file
    - Note the mixin takes in multiple parameters:
        ``` css
         @mixin myThemeMixin ($primary, $secondary) {
           :root {
             --my-css-variable: $primary;
             --my-second-variable: darken($secondary, 5%);
           }
         }
        ```
    - Referencing style:
      ``` css
       @include myThemeMixin(#181818, #323232);
      ``` 
2. Use WebCompiler to compile the stylesheet

### Current behavior
The compiled file contains the SASS variables names instead of the passed variable values
``` css
:root {
  --my-css-variable: $primary;
  --my-second-variable: darken($secondary, 5%);
}
```

### Expected behavior
The compiled stylesheets should not contain any references to SASS variables
