### ISSUE TITLE
SCSS compiler do not exclude CSS style Comments

### ISSUE THREAD

**Issue by fspezi** [failwyn/WebCompiler#57]
### Installed product versions
- Visual Studio: Microsoft Visual Studio Community 2022 (64 bit)
- This extension: 1.14.8

### Description
The SCSS compiler do not exclude Comments: it fire error about issue inside commented code.

### Steps to recreate

This code fire the error in compilation:

```scss

    .style-home {

        @mixin setDimension($width, $height, $maxHeight) {
            &,
            .xlTouchslide {
                height: $height;
                max-height: $maxHeight;
            }
        }

        $slideHeight-base: "100vh";
        
        /**
        @each $bp, $bpCfg in $edge-navbar-footer--bp {
           @include media-breakpoint-up($bp) {
               @if (map.get($bpCfg, "fixed") == true) {
                   $slideHeight: $slideHeight-base + " - " + map.get($bpCfg, "height");
                   @include setDimension(100%, 100vh, calc(#{$slideHeight}));     // <<--- CODE WITH ERROR
               }
               @else {
                   @include setDimension(100%, 100vh, calc(#{$slideHeight-base}));
               }
           }
        }
         *
         */

        @include setDimension(100%, 100vh, calc(#{$slideHeight-base}));

        margin-top: 0;
    }
```

### Current behavior
This is the LOG of WebCompiler

```
    ╷
127 │         // *            @include setDimension(100%, 100vh, calc(#{$slideHeight}));
    │                                                                   ^^^^^^^^^^^^
    ╵
  Css\WebSite\layout-web\_page-slideshow-head.scss 127:67  @import
  Css\WebSite\layout-web\_-OUT-.scss 9:9                   @import
  Css\WebSite\_WebSite.scss 9:9                            @import
  Css\Compilers\Web.scss 94:9                              root stylesheet
```

### Expected behavior

I expect that the text in comment must be excluded by compilation.

Thanks
